---
title: "Lab 1"
output: pdf_document
---
Hong Xu  
August 24, 2015   
Team: Hong Xu

1. **Task 1**
```{r, echo = TRUE}
set.seed(1234)
Var1 <- rnorm(n=100)
Var2 <- rnorm(n=100)
Var3 <- rnorm(n=100)
```

2. **Task 2**
```{r, echo = TRUE}
print(Var1)
print(Var2)
print(Var3)
```

3. **Task 3**
```{r, echo = TRUE}
myMatrix <- matrix(Var1, 10, 10)
```

4. **Task 4**
```{r, echo = TRUE}
# reference: help document of function layout

old.par <- par(no.readonly = TRUE) # save default, for resetting
nf <- layout(matrix(c(2, 0, 1, 3), 2, 2, byrow=TRUE), widths=c(3,1), heights=c(1,3), respect=TRUE)
par(mar=c(3,3,1,1))
# scatter plot of Var1 vs. Var2
plot(x=Var2, y=Var1, pch=16, cex=1, col="darkorange", main='Scatterplot Var1 vs. Var2')
# histograms
xhist <- hist(Var2, plot=FALSE)
yhist <- hist(Var1, plot=FALSE)
top <- max(c(xhist$counts, yhist$counts))
par(mar=c(0,3,2,1))
barplot(xhist$counts, axes=FALSE, ylim=c(0,top), space=0, col="deepskyblue", border="white")
par(mar=c(3,0,1,2))
barplot(yhist$counts, axes=FALSE, xlim=c(0,top), space=0, col="deepskyblue", border="white", horiz=TRUE)

par(old.par) # reset to default
```

5. **Task 5**
```{r, echo = TRUE}
taskFunction <- function(nameVector, ...) {  
  
  # 
  # Input
  # nameVector: a vector of length p containing the names of the vectors
  # ...: p vectors that need to get combined
  #
  # Output
  # a pdf file that contains boxplot
  # the mean value of the result vector
  #
   
  # combine vectors into dataframe
  df <- data.frame(...)
  p <- ncol(df)
  
  if (length(nameVector) != p) {
    print("Length of nameVector does not equal to p...")
    return(FALSE)
  } 
  
  colnames(df) <- nameVector 
  # get row wise maximum
  rowMax <- apply(df, 1, max)
  # and store it
  save(rowMax, file="row_max_vector.RData")
  # plot boxplot and store to pdf
  pdf("Xu_Hong_Solutions_myPlot.pdf")
  boxplot(rowMax, col="lightgray", main="Boxplot of row-wise max")
  dev.off()
  # return mean
  return(mean(rowMax)) 
}
taskFunction(c("Var1", "Var2"), Var1, Var2)

```

